logo_title: Miozus 喵族

style: black

# 原来没有设定，我自己添加的 元素和js控制，跟随星期变换
# favicon: img/favicon_3.ico

menu:
  作品: /project
  关于: /about

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: 8BYGM0HF1jIBeGuvqMy7Anub-gzGzoHsz
  appKey: PgYFLgalcyBa8phx4V29jiaI

highlight:
  enable: false